{
 "title": "Spring HTTP Example",
 "tags": [
  "spring",
  "http"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "_instance_label_name", "query": "${VAR__INSTANCE_LABEL_NAME}" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{job=\"$job\",}, $_instance_label_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS by URI",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri) (irate(http_server_requests_seconds_count{job=\"$job\", $_instance_label_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RPS by $_instance_label_name",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by($_instance_label_name) (irate(http_server_requests_seconds_count{job=\"$job\", $_instance_label_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(status) (irate(http_server_requests_seconds_count{job=\"$job\", $_instance_label_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Avg Latency (by $_instance_label_name)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by($_instance_label_name) (increase(http_server_requests_seconds_sum{job=\"$job\", $_instance_label_name=~\"$instance\"}[$__rate_interval]))\n / \n(sum by($_instance_label_name) (increase(http_server_requests_seconds_count{job=\"$job\", $_instance_label_name=~\"$instance\"}[$__rate_interval])) != 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg Latency (by outcome)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(outcome) (increase(http_server_requests_seconds_sum{job=\"$job\", $_instance_label_name=~\"$instance\"}[$__rate_interval]))\n / \n (sum by(outcome) (increase(http_server_requests_seconds_count{job=\"$job\", $_instance_label_name=~\"$instance\"}[$__rate_interval])) != 0)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by(exception) (increase(http_server_requests_seconds_count{exception!=\"None\", job=\"$job\", $_instance_label_name=~\"$instance\"}[$__range]))) > 0"
    }
   ]
  },
  {
   "title": "Top 10 Longest Requests",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, max (max_over_time(http_server_requests_seconds_max{job=\"$job\", $_instance_label_name=~\"$instance\"}[$__range])) by(uri, outcome, method))"
    },
    {
     "expr": "sum (increase(http_server_requests_seconds_count{job=\"$job\", $_instance_label_name=~\"$instance\"}[$__range])) by(uri, outcome, method)"
    },
    {
     "expr": "sum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_sum{job=\"$job\", $_instance_label_name=~\"$instance\"}[$__range])\n)\n/ \nsum by(uri, outcome, method) (\n    increase(http_server_requests_seconds_count{job=\"$job\", $_instance_label_name=~\"$instance\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum by (method, uri, exception, status) (\n        increase(\n            http_server_requests_seconds_count{job=\"$job\", $_instance_label_name=~\"$instance\", status=~\"5..|400|499\"}[$__range]\n        )\n    ) > 0, \n    'uri', \n    '$1/*$2', \n    'uri', \n    '(.*)\\\\/\\\\{.+\\\\}(.*)'\n)"
    }
   ]
  }
 ]
}